#!/usr/bin/env python3
import sys, os
sys.path.insert(0, '/home/minhvnq/Desktop/Web/MinhOmega.github.io')
import blog_generator as bg

# Read existing slugs
with open('/tmp/existing_slugs.txt') as f:
    existing = set(line.strip() for line in f)

def safe_blog(title, slug, date, desc, tags, cat, sections):
    if slug in existing:
        slug = slug + "-complete-guide"
    bg.write_blog(title, slug, date, desc, tags, cat, sections)

# ============================================================
# BLOG 1021: Jest Complete Testing Framework Guide
# ============================================================
safe_blog(
    "Jest: The Complete JavaScript Testing Framework Guide",
    "jest-complete-javascript-testing-framework-guide",
    "2020-06-15",
    "Master Jest testing: configuration, matchers, mocking, coverage, snapshot testing, and advanced patterns for JavaScript and TypeScript projects.",
    ["Testing", "Jest", "JavaScript", "Unit Testing"],
    "testing",
    [
        ("Why Jest Dominates JavaScript Testing",
         "Jest has become the de facto standard for testing JavaScript applications, powering test suites at Facebook, Google, Airbnb, and thousands of other companies worldwide. Its zero-config philosophy means you can start writing tests immediately without spending hours configuring build tools, assertion libraries, and mocking frameworks. Jest provides everything out of the box: a test runner, assertion library, mocking capabilities, code coverage reporting, and snapshot testing. The framework was originally designed for React component testing but has evolved into a universal testing solution for any JavaScript or TypeScript project.\n\nWhat sets Jest apart from competitors like Mocha, Jasmine, or Vitest is its focus on developer experience. Parallel test execution, intelligent test re-running, and a clear assertion API make writing and maintaining tests feel natural rather than burdensome. The built-in code coverage with Istanbul integration means you always know which parts of your codebase lack test coverage. Jest's watch mode intelligently re-runs only tests affected by your changes, making the feedback loop nearly instantaneous during development.\n\nThe testing pyramid — with many unit tests at the base, fewer integration tests in the middle, and minimal end-to-end tests at the top — maps perfectly to Jest's capabilities. Its fast execution speed makes running thousands of unit tests practical, while its module mocking system enables true isolation for integration testing. Understanding Jest deeply is essential for any modern JavaScript developer who values code quality and maintainability."),
        ("Setting Up Jest in Your Project",
         "Installing Jest requires just a single npm command, but proper configuration unlocks its full potential. For a basic JavaScript project, you need the jest package as a dev dependency. TypeScript projects additionally need ts-jest and @types/jest. The jest.config.js file controls all behavior: which files to test, how to transform code, where to find modules, and what coverage thresholds to enforce.\n\nThe most important configuration options are testMatch (which files Jest considers tests), transform (how to process different file types), moduleNameMapper (path aliases for clean imports), and setupFilesAfterFramework (global test initialization). For Next.js projects, you typically need @testing-library/jest-dom for DOM-specific matchers and next/jest for proper module resolution. The configuration below sets up a modern TypeScript project with path aliases and custom module resolution."),
        ("Writing Effective Test Suites",
         "Effective tests follow the Arrange-Act-Assert pattern, clearly separating setup from execution from verification. Jest provides describe blocks for organizing related tests and it/test blocks for individual assertions. Descriptive test names that read like specifications help documentation and debugging. Instead of test('user creation'), write test('creates a new user with valid email and password') to capture intent.\n\nMatchers form the assertion backbone: expect(value).toBe(exact), toEqual(deep), toBeTruthy(), toContain(item), toThrow(error), and toBeGreaterThan(number). For asynchronous code, use async/await with expect patterns or return promises directly. Jest waits for the promise to resolve before completing the test. The expect.assertions(n) pattern ensures a specific number of assertions run, preventing false positives from unexecuted code paths.\n\nGroup related tests with describe blocks and use beforeEach/afterEach for shared setup and teardown. Keep test files focused — one test file per source module — and import only what you need. Avoid testing implementation details; test behavior instead. A component that renders correctly with certain props should be tested by asserting on its output, not on which internal functions were called."),
        ("Mocking and Dependency Isolation",
         "Mocking is Jest's superpower. The jest.fn() function creates mock functions you can inspect for calls, arguments, and return values. jest.mock('module-path') replaces entire modules with auto-mocked versions. jest.spyOn(object, 'method') wraps existing methods to intercept calls while preserving original behavior unless explicitly overridden.\n\nFor API testing, mock fetch or axios with controlled responses. For database operations, mock the ORM or query builder. The key principle is to mock at the boundary of your system — external services, databases, file systems — not internal business logic. Over-mocking leads to tests that pass even when the code is broken because they test the mock rather than the actual integration.\n\nModule mocking with jest.mock works automatically for ES modules when using the factory parameter. You can mock only specific exports while keeping others real, enabling partial mocking for complex dependencies. The jest.requireActual() function lets you access the real implementation when needed inside a mock factory, giving you fine-grained control over which parts of a dependency to replace."),
        ("Snapshot Testing for UI Components",
         "Snapshot testing captures the rendered output of a component and compares it against a stored reference. When the output changes, Jest flags the difference and asks you to either accept the new snapshot or fix the regression. This is particularly valuable for React component testing where visual changes should be intentional and reviewed.\n\nJest stores snapshots as .snap files in a __snapshots__ directory next to your test files. These are committed to version control so the team reviews any snapshot changes in pull requests. The toMatchSnapshot() matcher creates the comparison, while toMatchInlineSnapshot() embeds the expected output directly in the test file for easier review.\n\nSnapshot testing has trade-offs. It catches unintended visual regressions but can become noisy if components change frequently. Use snapshot testing for stable UI components like form elements, navigation bars, and layout structures. Avoid snapshots for rapidly evolving components where the maintenance cost of updating snapshots outweighs the benefit. Consider using custom serializers to focus snapshots on the most important aspects of your output."),
        ("Code Coverage Configuration and Enforcement",
         "Jest collects code coverage automatically with the --coverage flag, powered by Istanbul under the hood. The coverage report shows line, branch, function, and statement coverage percentages for every file. Configure coverage thresholds in jest.config.js to fail the build when coverage drops below acceptable levels.\n\nSetting coverage thresholds enforces quality gates: global thresholds for the entire project and per-path thresholds for critical modules. A typical configuration requires 80% line coverage globally but 95% for business-critical services. The collectCoverageFrom array specifies which files to include, excluding test files, configuration, and generated code from the report.\n\nCoverage reports can be generated in multiple formats: text (console output), lcov (for CI integration), html (browseable reports), and json (for tooling). CI pipelines typically upload lcov reports to services like Codecov or Coveralls for trend tracking and pull request annotations. The coveragePathIgnorePatterns option excludes directories like node_modules, build output, and test utilities from coverage calculations, ensuring the numbers reflect actual application code."),
        ("Advanced Patterns: Timers, Environment, and Custom Matchers",
         "Jest's fake timer system replaces setTimeout, setInterval, Date.now, and performance.now with controllable versions. jest.useFakeTimers() activates them, jest.advanceTimersByTime(ms) simulates time passing, and jest.runAllTimers() executes all pending callbacks. This is essential for testing debounce logic, polling mechanisms, animation sequences, and any time-dependent code without waiting for real time to pass.\n\nCustom matchers extend expect() with domain-specific assertions. Create them with expect.extend() to add matchers like toBeValidEmail(), toHaveResponseStatus(200), or toMatchUserSchema(). Custom matchers improve test readability and reduce duplication across test files. They return an object with pass (boolean) and message (function returning the error description), following Jest's matcher protocol.\n\nThe testEnvironment configuration option controls the global context: 'node' for server-side code and 'jsdom' for browser-like testing. jsdom provides DOM APIs like document, window, and navigator, making it suitable for React testing. Modern Jest defaults to jsdom but you should explicitly set it per-project. You can also configure the test environment per-file using docblock comments for projects mixing Node.js and browser code."),
    ]
)

# ============================================================
# BLOG 1022: Vitest vs Jest Performance Comparison
# ============================================================
safe_blog(
    "Vitest vs Jest: Performance Comparison and Migration Guide",
    "vitest-vs-jest-performance-comparison-migration",
    "2024-03-20",
    "Compare Vitest and Jest: speed benchmarks, feature parity, migration strategies, and when to choose each testing framework.",
    ["Testing", "Vitest", "Jest", "Vite"],
    "testing",
    [
        ("The Rise of Vitest in the Testing Ecosystem",
         "Vitest emerged as a Vite-native test runner that leverages the same transformation pipeline as your production build, eliminating the configuration duplication that plagues Jest-with-Vite setups. Created by Anthony Fu and maintained under the Vue.js ecosystem, Vitest has rapidly gained adoption across React, Vue, Svelte, and vanilla JavaScript projects. Its compatibility with Jest's API means most test suites migrate with minimal changes — often just updating import paths and configuration files.\n\nThe fundamental architectural difference is how each framework handles module transformation. Jest uses its own transform layer, requiring separate configuration for Babel, TypeScript, or SWC. Vitest piggybacks on Vite's already-configured transform pipeline, meaning your tests use the exact same module resolution, aliases, and transforms as your development server. This eliminates an entire class of 'works in dev but fails in test' bugs caused by divergent transformation configurations.\n\nVitest runs tests in the same Vite dev server context by default, enabling features like hot module replacement for tests (watch mode that updates tests without full re-runs) and native ESM support without hacks. The framework also supports in-source testing — writing tests inside the source files themselves, guarded by import.meta.env.DEV conditionals, a pattern popular in the Vue ecosystem."),
        ("Speed Benchmarks: Where Vitest Wins",
         "Benchmarks consistently show Vitest outperforming Jest by 2-10x depending on the test suite characteristics. The speed advantage comes from three sources: shared transformation cache with Vite, native ESM execution without CommonJS transformation overhead, and Vitest's use of worker threads instead of Jest's child process model. For a typical React project with 500 tests, Vitest completes in 3-5 seconds while Jest takes 12-20 seconds.\n\nThe transformation overhead is the biggest factor. Jest transforms every imported module fresh for each test file, even when the same module appears in hundreds of test files. Vite's module graph caches transformations once and reuses them, meaning the second test importing a module pays near-zero transformation cost. For large monorepos with shared libraries, this caching effect multiplies dramatically.\n\nWatch mode performance tells an even starker story. Vitest's watch mode leverages Vite's HMR to re-run only tests affected by file changes, with sub-second feedback loops. Jest's watch mode uses its own file watcher and test dependency graph, which works but is slower to detect changes and determine affected tests. For the iterative development workflow of writing tests alongside code, Vitest's near-instant feedback fundamentally changes the testing experience."),
        ("Feature Comparison: Where They Stand",
         "Vitest implements nearly all of Jest's API surface: describe, it, expect, beforeEach, afterEach, jest.fn() becomes vi.fn(), jest.mock() becomes vi.mock(), and snapshot testing works identically. The migration path is genuinely smooth — most projects report completing migration in under an hour. Vitest also adds features Jest lacks: native TypeScript support without ts-jest, CSS module mocking out of the box, and browser-mode testing for real browser environments.\n\nHowever, Jest still leads in some areas. Jest's module mocking is more battle-tested with complex scenarios like partial mocking and dynamic imports. Jest's ecosystem of custom reporters, CI integrations, and third-party matchers is more mature. Jest also has better support for legacy CommonJS codebases and has more predictable behavior with global state leakage between tests.\n\nVitest introduces unique features beyond Jest parity. Inline snapshots work without file system access. The bench() function provides built-in benchmarking. Type testing with expectTypeOf and assertType enables compile-time assertion checking. The browser mode runs tests in actual browsers using Playwright, enabling real DOM testing without jsdom's limitations. These extras make Vitest not just a Jest replacement but an evolution of the testing paradigm."),
        ("Migration Strategy: Jest to Vitest",
         "Migration begins with installing vitest and @vitest/coverage-v8 (replacing Istanbul for coverage). Create a vitest.config.ts that mirrors your jest.config.js: map moduleNameMapper to resolve aliases, transform to plugins, and testMatch to include. Vitest auto-detects many Jest configuration patterns, reducing manual mapping.\n\nThe core code changes are minimal. Replace jest.fn() with vi.fn(), jest.mock() with vi.mock(), jest.spyOn() with vi.spyOn(), and jest.useFakeTimers() with vi.useFakeTimers(). The beforeEach, afterEach, describe, and it/test functions are identical. Snapshot testing works unchanged. Most test files need zero modifications beyond the mock function replacements.\n\nFor gradual migration, Vitest's --passWithNoTests flag allows running both frameworks in parallel. Start by migrating your simplest test files to Vitest while keeping complex ones on Jest. The vite.config.ts test configuration coexists with jest.config.js during transition. CI pipelines can run both test suites until migration is complete, ensuring no test coverage gaps during the transition period."),
        ("Configuration Deep Dive",
         "Vitest configuration lives in vitest.config.ts or inside the test key of vite.config.ts. The globals option enables Jest-compatible global functions without importing, matching Jest's default behavior. The environment option sets the default test environment: 'node', 'jsdom', or 'happy-dom' (a faster jsdom alternative). Environment matchers can assign different environments per file pattern.\n\nCoverage configuration uses @vitest/coverage-v8 or @vitest/coverage-istanbul. V8 coverage is faster and more accurate than Istanbul's instrumentation-based approach. Configure thresholds, reporters, and include/exclude patterns similar to Jest but with Vitest's configuration syntax. The coverage.all option includes untested files in the report, giving a complete picture of your test coverage.\n\nPool configuration controls test parallelism. Vitest uses worker threads by default (pool: 'threads') but supports pool: 'forks' for process-based isolation (useful when tests modify global state). The poolOptions configuration controls thread/fork count, memory limits, and worker isolation levels. For CI environments with limited resources, setting maxThreads and minThreads prevents resource exhaustion while maintaining parallelism benefits."),
        ("When to Choose Vitest vs Jest",
         "Choose Vitest when your project uses Vite as its build tool — the shared configuration alone eliminates hours of maintenance. Choose Vitest when test execution speed is a bottleneck in your CI pipeline or development workflow. Choose Vitest when you want native TypeScript support without configuring ts-jest or Babel transforms. Choose Vitest when you value modern ESM-first architecture.\n\nChoose Jest when your project is a large, stable codebase with extensive Jest configuration and custom matchers that would be costly to migrate. Choose Jest when you depend on specific Jest ecosystem packages that lack Vitest equivalents. Choose Jest when your team has deep Jest expertise and the performance improvement doesn't justify the migration effort. Choose Jest for React Native projects where Jest integration is deeply embedded in the framework tooling.\n\nThe testing framework landscape continues evolving. Both Jest and Vitest are actively maintained and improving. The decision isn't permanent — you can always migrate later when the timing is right. What matters most is that your project has comprehensive, well-written tests. The framework that encourages your team to write more tests is the right choice for your project."),
    ]
)

# ============================================================
# BLOG 1023: Playwright End-to-End Testing Guide
# ============================================================
safe_blog(
    "Playwright End-to-End Testing: The Complete Developer Guide",
    "playwright-end-to-end-testing-complete-guide",
    "2023-08-10",
    "Master Playwright E2E testing: browser automation, test fixtures, visual regression, API mocking, and CI integration patterns.",
    ["Testing", "Playwright", "E2E", "Automation"],
    "testing",
    [
        ("Why Playwright Over Selenium and Cypress",
         "Playwright, built by Microsoft, has rapidly become the preferred end-to-end testing framework for modern web applications. It supports Chromium, Firefox, and WebKit from a single API, enabling true cross-browser testing without browser-specific test code. Unlike Selenium's WebDriver protocol, Playwright communicates directly with browser engines through the Chrome DevTools Protocol and equivalent mechanisms, resulting in faster execution, better reliability, and access to advanced browser features.\n\nCypress, while excellent for component and simple E2E tests, is limited to Chromium-based browsers and runs inside the browser itself, creating architectural constraints for testing scenarios involving multiple tabs, iframes, or cross-origin requests. Playwright runs outside the browser as a Node.js process, giving it unrestricted control over the browser including multi-tab scenarios, authenticated states, and file system access.\n\nPlaywright's auto-wait mechanism eliminates the flaky tests caused by timing issues that plague Selenium suites. Instead of explicit waits and sleep calls, Playwright automatically waits for elements to be actionable — visible, enabled, and not obscured — before performing actions. This intelligent waiting, combined with retry-able assertions using expect(locator), makes Playwright tests remarkably stable even on slow-loading or dynamically updating pages."),
        ("Setting Up Playwright in Your Project",
         "The official create-playwright CLI scaffolds a complete testing project with sensible defaults. Running npm init playwright installs the framework, downloads browser binaries, creates a playwright.config.ts, and generates example test files. The configuration file controls projects (browsers to test), webServer (auto-starting your dev server), timeouts, retries, and output directories.\n\nThe playwright.config.ts is the nerve center of your test suite. Define projects for each browser and device: Desktop Chrome, Desktop Firefox, Desktop Safari, Mobile Chrome, and Mobile Safari. The webServer configuration starts your development server before tests run, eliminating manual startup. baseURL configuration points all page.goto() calls to your development server, keeping test code clean.\n\nBrowser binaries are downloaded to a cache directory (~/.cache/ms-playwright) and are separate from your system browsers. This ensures consistent behavior across development machines and CI servers. The npx playwright install command manages binary downloads, and --with-deps installs system dependencies needed for headless execution on Linux CI servers."),
        ("Writing Robust Playwright Tests",
         "Playwright tests use the test and expect imports from @playwright/test. Each test receives a page fixture representing a browser tab, along with context (browser context for isolation) and browser (the browser instance). Tests are async functions that perform actions on page objects and assert results using Playwright's expect API with web-first assertions.\n\nLocators are Playwright's recommended way to find elements. Unlike CSS selectors or XPath, locators are designed for testing: page.getByRole('button', { name: 'Submit' }) finds a button by its accessible role and text. page.getByLabel('Email') finds form inputs by their associated label. page.getByTestId('submit-btn') uses data-testid attributes for stable element selection that doesn't break with style changes. These locator strategies produce tests that are resilient to implementation details while remaining readable.\n\nPlaywright's actions — click, fill, type, press, selectOption, check, uncheck — automatically wait for the target element to be ready. Assertions like expect(page).toHaveTitle(), expect(locator).toBeVisible(), expect(locator).toHaveText(), and expect(locator).toHaveValue() include auto-retrying with configurable timeouts. This combination of auto-waiting actions and retrying assertions produces tests that work reliably without explicit waits or sleep calls."),
        ("Advanced Patterns: Fixtures and Page Objects",
         "Fixtures are Playwright's dependency injection system, providing test-specific data and objects. The base test.extend() method creates custom fixtures for database connections, authenticated pages, API clients, or any shared test infrastructure. Fixtures are lazily initialized — they're created only when a test requests them — and automatically torn down after the test completes.\n\nThe authenticated page pattern creates a fixture that handles login once and reuses the authenticated browser context across tests. This avoids logging in for every test, reducing execution time while maintaining test isolation. The storageState approach saves the authenticated session to a file and replays it for subsequent tests, a pattern that scales well for applications with complex authentication flows.\n\nPage Object Model (POM) encapsulates page interactions in reusable classes. A LoginPage object provides methods like login(email, password) and error messages, hiding the selectors and interaction details. While Playwright's official documentation recommends using locators directly in tests for simplicity, POMs remain valuable for large test suites where multiple tests interact with the same complex pages. The key is choosing the abstraction level that reduces duplication without obscuring test intent."),
        ("Visual Regression Testing with Playwright",
         "Playwright includes built-in visual comparison testing through the toHaveScreenshot() assertion. This captures a screenshot of an element or page and compares it pixel-by-pixel against a stored baseline image. When differences exceed the configured threshold, the test fails and produces a diff image highlighting the changes.\n\nVisual testing configuration includes maxDiffPixels for tolerance, threshold for per-pixel color difference, and animations handling to prevent flaky comparisons from CSS animations. The mask option hides dynamic content like timestamps or user avatars that change between test runs. Clip regions allow testing specific page areas while ignoring irrelevant sections like ads or dynamic footers.\n\nThe npx playwright test --update-snapshots command regenerates baseline images after intentional UI changes. In CI, run visual tests in Docker containers with consistent font rendering and screen sizes to prevent false positives from environment differences. Store baseline images in version control alongside test files, treating visual changes with the same code review rigor as functional changes."),
        ("API Testing and Network Interception",
         "Playwright excels at API testing and network manipulation. The page.route() method intercepts network requests before they reach the server, enabling mocking API responses, modifying request headers, and simulating error conditions. This is invaluable for testing edge cases like network failures, slow responses, empty data sets, and rate limiting without maintaining separate API mock servers.\n\nThe APIRequestContext provides standalone API testing capabilities independent of browser automation. Use it to test REST APIs, set up test data, and verify backend behavior. The request fixture in test functions provides a pre-configured context that respects the baseURL configuration. Combine browser tests with API tests in the same test file to verify both frontend behavior and backend contract compliance.\n\nNetwork interception patterns include mocking successful responses with fixture data, simulating network errors by aborting requests, throttling response speed to test loading states, and capturing outgoing requests to verify correct API calls from the frontend. The page.waitForResponse() method waits for specific network requests to complete, enabling assertions on response bodies and status codes without polluting application code with test hooks."),
        ("CI Integration and Parallel Execution",
         "Playwright integrates with all major CI platforms: GitHub Actions, GitLab CI, CircleCI, and Jenkins. The official Docker image (mcr.microsoft.com/playwright) includes all browser binaries and system dependencies. GitHub Actions can use the setup-playwright action for optimized caching of browser binaries, reducing CI setup time from minutes to seconds.\n\nParallel test execution is configured via the workers option in playwright.config.ts. By default, Playwright uses half the available CPU cores. For CI, set workers based on your runner's CPU count. Tests are sharded across workers at the file level — each test file runs entirely in one worker. The --shard=1/3 flag on the CLI enables distributing test files across multiple CI machines for maximum parallelism.\n\nThe retry configuration handles flaky tests in CI without blocking deployments. Set retries: 2 to retry failed tests twice before reporting failure. Combined with the reporter system (HTML, JSON, JUnit for CI integration), Playwright provides comprehensive test reporting. The HTML reporter generates a browseable report with screenshots, traces, and video recordings of failed tests, making debugging CI failures straightforward without reproducing locally."),
    ]
)

# ============================================================
# BLOG 1024: Cypress Component Testing Patterns
# ============================================================
safe_blog(
    "Cypress Component Testing: Patterns and Best Practices",
    "cypress-component-testing-patterns-best-practices",
    "2023-05-20",
    "Master Cypress component testing: mounting components, testing interactions, stubbing APIs, and integrating with React and Vue.",
    ["Testing", "Cypress", "Component Testing", "React"],
    "testing",
    [
        ("Understanding Cypress Component Testing",
         "Cypress component testing mounts individual components in a real browser, rendering them in isolation while providing the full Cypress API for interaction and assertion. Unlike unit tests that run in jsdom, Cypress component tests exercise components in a genuine browser environment with real CSS rendering, real DOM events, and real layout calculations. This catches visual and interaction bugs that jsdom-based tests miss, such as CSS conflicts, event bubbling issues, and layout overflow problems.\n\nThe architecture differs fundamentally from Cypress E2E testing. E2E tests visit a running application; component tests mount individual components directly into the browser viewport. Cypress intercepts the component import, bundles it with its dependencies using Vite or Webpack, and renders it inside a test harness that provides mounting utilities and assertion helpers. The component runs with its actual styles, child components, and browser APIs — no mocking the rendering environment.\n\nComponent testing bridges the gap between fast-but-shallow unit tests and thorough-but-slow E2E tests. A component test can verify that a form validates input, displays errors, submits data, and shows a loading spinner — all without routing, authentication, or backend services. This makes component tests faster and more focused than E2E tests while catching more real-world bugs than jsdom unit tests."),
        ("Setting Up Cypress for Component Testing",
         "Cypress component testing requires configuration in cypress.config.ts specifying the component testing devServer. For React with Vite, the devServer function imports defineConfig from vite, merges your vite.config.ts settings, and returns the Cypress Vite dev server. For Webpack projects, use the Cypress Webpack dev server with your webpack configuration. The key is ensuring the dev server can resolve your project's imports, aliases, and transforms.\n\nThe cypress/support/component.ts file initializes the testing environment: importing mount from @cypress/react (or @cypress/vue), adding global styles, and registering custom commands. The mount function is the Cypress equivalent of React Testing Library's render — it takes a JSX component and optional configuration like props, routing context, or state providers, then renders it in the browser viewport.\n\nCypress automatically detects component test files using the specPattern configuration, typically *.cy.tsx or *.cy.ts. Each test file can mount different components, and Cypress handles the cleanup between tests — unmounting the previous component before mounting the next one. This isolation prevents state leakage between tests while maintaining the browser context for consistent behavior."),
        ("Writing Component Tests with Mount and Interact",
         "The mount function is the entry point for every component test. Mount your component with its required props and any necessary providers: mount(<UserProfile user={mockUser} onEdit={cy.stub()} />). Cypress renders the component and makes it available for interaction and assertion using the same selectors and commands used in E2E tests.\n\nInteraction follows the user-centric pattern: cy.get('[data-testid="submit-btn"]').click(), cy.get('input[name="email"]').type('test@example.com'), cy.get('select').select('option-value'). Cypress waits for elements to be actionable before performing actions, reducing flaky tests from timing issues. Chain assertions after interactions: cy.get('.error-message').should('be.visible').and('contain', 'Invalid email').\n\nTesting component callbacks uses cy.stub() to create spy functions. Pass the stub as a prop and assert it was called with expected arguments: const onSubmit = cy.stub(); mount(<Form onSubmit={onSubmit} />); cy.get('form').submit(); cy.then(() => expect(onSubmit).to.be.calledWith(expectedData)). The cy.then() callback ensures the assertion runs after the event handler completes, handling async callback scenarios correctly."),
        ("Testing with State Management and Context",
         "Components that depend on React Context, Redux stores, or other state management need their providers wrapped around the component during mounting. Create a custom mount function that wraps the component in necessary providers: function mountWithProviders(component, { store = createTestStore(), ...props } = {}) { return mount(<Provider store={store}>{component}</Provider>) }.\n\nFor Redux, create a test store with pre-loaded initial state matching the test scenario. This lets you test components in specific application states — a shopping cart with items, a user dashboard with loaded data, an error state — without navigating through the application to reach that state. The store also captures dispatched actions, enabling assertions on what actions a component triggers in response to user interactions.\n\nContext providers for themes, authentication, routing, and internationalization follow the same wrapper pattern. The mount function accepts options for overriding provider values, giving each test precise control over the environment. This pattern scales well — create a single mountWithProviders utility that all test files import, ensuring consistent provider configuration across your entire test suite."),
        ("Stubbing APIs and Network Requests",
         "Cypress intercepts network requests using cy.intercept(), enabling API mocking in component tests. Before mounting a component that fetches data, set up intercepts for its API endpoints: cy.intercept('GET', '/api/users', { fixture: 'users.json' }).as('getUsers'). After mounting, wait for the request: cy.wait('@getUsers') and assert on the response or the component's rendered state.\n\nThe fixture system stores mock API responses as JSON files in cypress/fixtures. This separates test data from test logic, making it easy to reuse mock responses across multiple tests. Fixtures can be loaded dynamically with cy.fixture('users.json') for use in assertions or as request bodies for POST/PUT operations.\n\nIntercept patterns include testing loading states (delay the response with delay: 1000), error handling (respond with statusCode: 500), empty states (respond with empty arrays), and pagination (respond with different data based on query parameters). The routeHandler function provides programmatic control, enabling dynamic responses based on request body, headers, or URL parameters. This flexibility lets you test every edge case your component should handle without maintaining a running API server."),
        ("Visual Testing and Snapshot Comparison",
         "Cypress supports visual testing through plugins like @percy/cypress for cloud-based visual regression testing or cypress-image-snapshot for local pixel comparison. Percy captures screenshots and compares them across builds, flagging visual regressions in pull requests with pixel-level diff highlighting.\n\nFor local visual testing, cypress-image-snapshot adds the matchImageSnapshot() command that captures screenshots and compares them against baseline images stored in the repository. Configure pixel thresholds and anti-aliasing options to prevent false positives from font rendering differences. The cypress run --env updateSnapshots=true flag regenerates baselines after intentional changes.\n\nVisual testing works best for components with stable layouts: cards, modals, navigation bars, and form elements. Avoid visual testing for components with dynamic content, third-party widgets, or data-dependent layouts. Use masking to hide dynamic regions while testing static areas. Combine visual testing with functional tests — visual tests catch appearance regressions while functional tests verify behavior — for comprehensive component coverage."),
        ("Best Practices and Common Pitfalls",
         "Test components the way users interact with them. Prefer getByRole or getByLabelText selectors over CSS class selectors that break when styles change. Test visible behavior — what the user sees and does — not implementation details like internal state variables or which helper functions were called. This philosophy, borrowed from Testing Library, produces tests that survive refactors.\n\nKeep component tests focused. Each test should verify one behavior or interaction chain. A test that mounts a component, fills a form, submits it, verifies the loading spinner, and checks the success message covers too many concerns. Split it into focused tests: one for form validation, one for submission loading state, one for success handling. Focused tests fail with clear, actionable error messages when something breaks.\n\nAvoid testing third-party library behavior. Don't test that React Router navigates or that Redux dispatches actions correctly — those are tested by their maintainers. Test your code's integration with these libraries: does your component pass the right props to the router? Does your action creator produce the correct payload? This boundary keeps your tests focused on your code and avoids brittle tests that break when dependencies update."),
    ]
)

# ============================================================
# BLOG 1025: React Testing Library Best Practices
# ============================================================
safe_blog(
    "React Testing Library Best Practices for Reliable Tests",
    "react-testing-library-best-practices-reliable-tests",
    "2023-03-15",
    "Write better React tests with Testing Library: queries, user events, async patterns, accessibility-first testing, and common mistakes.",
    ["Testing", "React", "Testing Library", "JavaScript"],
    "testing",
    [
        ("The Guiding Philosophy: Test Like a User",
         "React Testing Library (RTL) embodies a radical philosophy: your tests should resemble how users interact with your software. This means no testing implementation details like component state, internal methods, or lifecycle hooks. Instead, render components and interact with them through the same interfaces users use — clicking buttons, filling forms, reading text, and waiting for content to appear. Tests written this way survive refactors because they don't depend on internal structure.\n\nKent C. Dodds created Testing Library as a response to Enzyme's approach of testing component internals. Enzyme tests that assert on state values or shallow rendering output break whenever you refactor component implementation, even when behavior is identical. Testing Library queries elements the way users find them: by role, label text, placeholder text, or visible text content. When you rename a CSS class or move state from useState to useReducer, these tests pass unchanged because the rendered output didn't change.\n\nThe guiding principle is: the more your tests resemble the way your software is used, the more confidence they give you. This philosophy extends to every decision: prefer getByRole over getByTestId because screen readers use roles; prefer userEvent over fireEvent because userEvent simulates real keyboard and mouse behavior; prefer findBy over waitFor because findBy expresses intent more clearly."),
        ("Query Priority: Choosing the Right Selector",
         "Testing Library provides a priority order for queries, from most preferred to least. The top priority — getByRole — finds elements by their ARIA role, which is how assistive technology identifies them. getByRole('button', { name: 'Submit' }) finds a button with the text 'Submit', matching how a screen reader presents it. This catches accessibility issues automatically: if a div pretends to be a button without the button role, getByRole won't find it.\n\ngetByLabelText pairs form inputs with their labels, testing the actual form structure users interact with. getByPlaceholderText works for inputs with placeholder text, though placeholders shouldn't replace labels for accessibility. getByText finds non-interactive elements by their visible text content. getByDisplayValue finds form elements by their current value, useful after user interaction.\n\nThe lower-priority queries — getByAltText for images, getByTitle for title attributes, getByTestId for data-testid attributes — should be used only when higher-priority queries aren't applicable. The getByTestId escape hatch is valuable for elements with no accessible role, label, or text (like wrapper divs for styling), but overusing it signals potential accessibility problems. If you can't find an element with getByRole, ask whether the element should have an ARIA role or label."),
        ("User Events: Simulating Real Interactions",
         "Testing Library provides two event APIs: fireEvent (low-level DOM event dispatch) and userEvent (high-level user interaction simulation). Always prefer userEvent for its realistic behavior simulation. When a user types into an input, they press keys one at a time, triggering keydown, keypress, input, and keyup events. userEvent.type() simulates this complete sequence; fireEvent.change() only dispatches a synthetic change event that doesn't match real user behavior.\n\nThe @testing-library/user-event library (version 14+) uses a setup pattern: const user = userEvent.setup(); then await user.click(element), await user.type(input, 'text'), await user.keyboard('{Enter}'). The setup function accepts options like delay (for realistic typing speed), advanceTimers (for fake timer integration), and pointerEventsCheck (for pointer event validation).\n\nCommon interaction patterns include: filling and submitting forms (type into inputs, click submit), keyboard navigation (tab through elements, activate with Enter/Space), drag and drop (using pointer events), clipboard operations (copy/paste), and file uploads (using upload() with File objects). Each pattern requires the corresponding userEvent method — using fireEvent directly for complex interactions leads to incomplete event sequences that mask bugs."),
        ("Async Testing: findBy and waitFor",
         "Asynchronous UI updates — loading spinners, API responses, animations — require async testing patterns. Testing Library provides findBy queries (which retry until an element appears) and waitFor (which retries arbitrary assertions). findByRole, findByText, findByTestId return promises that resolve when the element is found within the timeout, or reject if it never appears.\n\nThe preferred pattern is: const element = await screen.findByText('Data loaded'); expect(element).toBeInTheDocument(). This clearly expresses 'wait for this text to appear, then verify it's there.' The findBy queries default to a 1000ms timeout, configurable globally via configure({ asyncUtilTimeout: 5000 }) or per-query with the timeout option.\n\nwaitFor wraps any assertion in a retry loop: await waitFor(() => { expect(mockApi).toHaveBeenCalledTimes(1) }). Use waitFor when you need to assert on something that isn't an element query — like mock function calls, URL changes, or console output. Never wrap a findBy in waitFor (it already retries) and never use waitForElementToBeRemoved without ensuring the element exists first. These common mistakes lead to confusing test failures."),
        ("Testing Forms, Modals, and Complex Interactions",
         "Form testing follows the user flow: render the form, fill inputs, submit, and assert on the result. Use userEvent.type() for text inputs, userEvent.selectOptions() for dropdowns, userEvent.click() for checkboxes and radio buttons, and userEvent.upload() for file inputs. After submission, assert on either the success message, the submitted data (captured through a mock function), or the validation error messages.\n\nModal testing requires handling focus management and portal rendering. When a modal opens, focus should move to the modal content. Test this with expect(modalContent).toHaveFocus(). When the modal closes, focus should return to the trigger element. Test keyboard interaction: Escape should close the modal, Tab should trap focus within the modal. These accessibility behaviors are critical to test because screen reader users depend on them.\n\nComplex interactions like drag-and-drop, multi-step wizards, and real-time collaboration require careful sequencing of user events and async assertions. For multi-step forms, test each step's validation before proceeding. For real-time features, mock the WebSocket or SSE connection and simulate incoming messages. The key principle remains: simulate exactly what a user would do, in the order they would do it, and assert on what they would see."),
        ("Mocking in Testing Library Tests",
         "Mock API calls using msw (Mock Service Worker) for the most realistic testing approach. MSW intercepts requests at the network level, meaning your application code makes real fetch/axios calls that get intercepted and responded to with mock data. This tests the complete request/response cycle including headers, error handling, and serialization.\n\nSet up MSW with a handlers file defining request interceptors: rest.get('/api/users', (req, res, ctx) => res(ctx.json(mockUsers))). In your test setup, start the MSW server before tests and reset handlers between tests. For component tests, use setupWorker for browser-based interception; for Node tests (jest/vitest), use setupServer.\n\nMock module dependencies with jest.mock() or vi.mock() for external libraries like analytics, logging, or third-party SDKs. Mock window.location, window.open, and navigator.clipboard for testing browser API interactions. The @testing-library/jest-dom package adds DOM-specific matchers like toHaveTextContent(), toHaveAttribute(), toHaveClass(), and toBeVisible() that make element assertions expressive and readable."),
        ("Common Mistakes and How to Avoid Them",
         "The most common mistake is testing implementation details through state assertions. Don't write expect(component.state.count).toBe(1) — instead, assert on the rendered output: expect(screen.getByText('Count: 1')).toBeInTheDocument(). If you find yourself reaching into component internals, reconsider what behavior you're actually trying to verify.\n\nUsing waitFor excessively signals potential issues. If every test needs waitFor wrapping, your components may be making too many sequential state updates or your mock setup isn't properly controlling async behavior. Fix the root cause rather than plastering waitFor everywhere. Properly mock APIs, use act() for state updates outside user events, and ensure your test environment supports the async patterns your components use.\n\nSkipping cleanup leads to test interdependence — tests that only pass when run in a specific order. Testing Library automatically unmounts components after each test when using the cleanup function (enabled by default in most test runners). If you're experiencing test pollution, verify that global state (window, document, localStorage) is reset between tests and that mock functions are cleared in beforeEach blocks."),
    ]
)

print("Blogs 1021-1025 created successfully!")
