#!/usr/bin/env python3
"""Generate 100 DevOps/Cloud/Infrastructure/CI-CD/Platform Engineering blogs (821-920)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import blog_generator as bg

# Each blog: (title, slug, date, description, tags, category, sections)
# sections: [(heading, body_text), ...] - body_text should be 300-500 words

blog_data = []

# ═══════════════════════════════════════════════════════════
# 821. Kubernetes Operators Deep Dive
# ═══════════════════════════════════════════════════════════
blog_data.append(("Kubernetes Operators Explained: Extending the Kubernetes API", "kubernetes-operators-explained-extending-the-kubernetes-api", "2020-08-15",
"Learn how Kubernetes Operators work, how to build custom controllers with the Operator SDK, and manage complex stateful applications on Kubernetes.",
["Kubernetes", "Operators", "DevOps", "Cloud Native"], "devops",
[("What Is a Kubernetes Operator?",
"A Kubernetes Operator is a method of packaging, deploying, and managing a Kubernetes application using custom resources and controllers. The Operator pattern extends the Kubernetes API by defining Custom Resource Definitions (CRDs) that represent domain-specific objects, and then implementing a control loop that watches those CRDs and reconciles the actual state of the cluster with the desired state described in each resource.\n\nThe core idea behind Operators was introduced by CoreOS in 2016 as a way to encode the operational knowledge of running complex stateful applications — such as databases, message queues, and monitoring systems — directly into software. Instead of requiring a human operator to manually perform tasks like scaling, failover, backup, and upgrades, an Operator automates these tasks by implementing them as code within a controller.\n\nAn Operator consists of two primary components: the Custom Resource Definition, which defines a new API object type in Kubernetes, and the controller, which is a control loop that watches for changes to those custom resources and takes action to move the current state toward the desired state. The controller interacts with the Kubernetes API server using client-go or a higher-level framework like kubebuilder or the Operator SDK.\n\nOperators are particularly valuable for stateful workloads because these applications require careful lifecycle management. A database Operator, for instance, knows how to initialize a cluster, add replicas, perform rolling upgrades without data loss, take scheduled backups, and restore from those backups if needed."),
("Understanding Custom Resource Definitions (CRDs)",
"Custom Resource Definitions (CRDs) are the mechanism by which Kubernetes allows you to define your own API objects without modifying the Kubernetes source code. When you create a CRD, the Kubernetes API server dynamically creates a new RESTful endpoint for the custom resource type, allowing users to create, read, update, and delete instances of that resource just like built-in resources such as Pods or Services.\n\nA CRD is itself a Kubernetes resource of kind CustomResourceDefinition. It specifies the API group, version, plural name, and schema for the custom resource. The schema defines what fields the custom resource supports, their types, default values, and validation rules. Starting with Kubernetes 1.16, CRDs must specify a structural OpenAPI v3 schema.\n\n```yaml\napiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition\nmetadata:\n  name: mysqlclusters.database.example.com\nspec:\n  group: database.example.com\n  versions:\n    - name: v1\n      served: true\n      storage: true\n      schema:\n        openAPIV3Schema:\n          type: object\n          properties:\n            spec:\n              type: object\n              properties:\n                replicas:\n                  type: integer\n                  minimum: 1\n  scope: Namespaced\n  names:\n    plural: mysqlclusters\n    kind: MySQLCluster\n```\n\nCRDs also support subresources like /status and /scale, additional printer columns for kubectl output, and conversion webhooks for migrating between API versions."),
("Building an Operator with the Operator SDK",
"The Operator SDK is a framework that simplifies the process of building Kubernetes Operators. It supports three approaches: Go-based Operators using the controller-runtime library, Ansible-based Operators that use Ansible playbooks for reconciliation logic, and Helm-based Operators that wrap an existing Helm chart in a controller.\n\nTo get started with a Go-based Operator:\n```bash\noperator-sdk init --domain example.com --repo github.com/example/mysql-operator\noperator-sdk create api --group database --version v1 --kind MySQLCluster --resource --controller\n```\n\nThis creates a project structure with a controllers directory for reconciliation logic, an api directory with CRD type definitions, and a config directory with Kubernetes manifests. The key file is the reconciler, containing the Reconcile method called whenever a MySQLCluster resource changes.\n\nThe Reconcile method receives a Request with the namespace and name of the triggering resource. Your controller fetches the current resource from the API server, inspects its spec, compares it to the actual state, and performs corrective actions. The Operator SDK also generates a Dockerfile, RBAC manifests, and a Makefile with common targets."),
("Reconciliation Loops and Controller Patterns",
"The reconciliation loop is the heart of every Kubernetes Operator. It follows a level-triggered design pattern: the controller is triggered whenever the observed state diverges from the desired state, and it takes action to converge them. This approach makes controllers resilient to failures since the next reconciliation will detect any drift.\n\nA well-designed reconciliation method follows these steps: fetch the custom resource, check if it is being deleted, fetch all owned child resources, compare desired state from spec with actual state, and perform create, update, or delete operations. The method returns a Result indicating whether to requeue.\n\nIdempotency is critical for the Reconcile method:\n```go\nfunc (r *MySQLClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {\n    cluster := &databasev1.MySQLCluster{}\n    if err := r.Get(ctx, req.NamespacedName, cluster); err != nil {\n        return ctrl.Result{}, client.IgnoreNotFound(err)\n    }\n    sts := r.desiredStatefulSet(cluster)\n    if err := r.createOrUpdate(ctx, sts); err != nil {\n        return ctrl.Result{}, err\n    }\n    return ctrl.Result{RequeueAfter: 30 * time.Second}, nil\n}\n```\n\nController-runtime provides helper functions for setting up watches on both primary and secondary resources."),
("Stateful Applications: Databases, Caches, and Message Queues",
"Running stateful applications on Kubernetes is a primary use case for Operators. Databases like PostgreSQL, MySQL, MongoDB, and etcd require careful handling of persistent volumes, replica configuration, leader election, and backup schedules. Caches like Redis Cluster need Operators to manage cluster topology and slot rebalancing. Message queues like Kafka require Operators to handle broker configuration and topic management.\n\nThe Postgres Operator by Zalando manages PostgreSQL clusters on Kubernetes. It handles creating Patroni-managed clusters, performing rolling updates, and automatically scaling instances. The Operator defines a postgresql CRD with spec including PostgreSQL version, number of instances, and resource limits.\n\nFor Kafka, the Strimzi Operator manages brokers, ZooKeeper ensembles, Kafka Connect workers, and the Kafka Bridge. It handles certificate generation for TLS, user management, and rolling updates that maintain availability.\n\nA critical aspect is handling PersistentVolumeClaims. The Operator must decide whether to use dynamically provisioned volumes, how to resize them, and what to do when a node fails. Kubernetes 1.24+ introduced CSI migration for most volume types, and Operators should be aware of storage class parameters."),
("Deploying and Managing Operators in Production",
"Deploying an Operator to production requires careful RBAC permissions, resource limits, high availability, and upgrade strategies. The Operator runs as a Deployment in a dedicated namespace. RBAC manifests define minimum permissions following least privilege.\n\nFor high availability, deploy with multiple replicas using leader election:\n```go\nmgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{\n    LeaderElection:   true,\n    LeaderElectionID: \"mysql-operator-lock\",\n})\n```\n\nOperator Lifecycle Manager (OLM) manages installation, upgrade, and lifecycle of Operators. OLM provides CatalogSource for Operator packages, Subscription for tracking updates, and InstallPlan for orchestrating installation.\n\nMonitoring involves exposing metrics about reconciliation latency, error rates, and queue depths. Track reconciliation duration histograms, number of watched resources, and failed reconciliation attempts. Alert on failures and high latency to detect issues before they affect managed applications."),
("Advanced Operator Patterns: Webhooks and Status Subresources",
"Beyond the basic reconciliation loop, advanced Operator patterns include admission webhooks for validation and defaulting, status subresources for separating spec from observed state, and aggregated APIs.\n\nAdmission webhooks intercept and modify resources before they are persisted. A validating webhook rejects resources that violate business rules. A mutating webhook applies defaults:\n\n```go\n// +kubebuilder:webhook:path=/mutate-database-example-com-v1-mysqlcluster,mutating=true,failurePolicy=fail\ntype MySQLClusterDefaulter struct{}\n```\n\nThe status subresource is a separate endpoint holding observed state. By enabling /status, updates to status are separated from spec updates, allowing the controller to update status without triggering spec reconciliation. Status fields typically include conditions, observed generation, and resource-specific state.\n\nFor Operators needing complex APIs beyond CRDs, aggregated API servers can be registered as extensions to the Kubernetes API. This is appropriate for custom serialization or proxying to backend services, though aggregated APIs are significantly more complex than CRD-based Operators.")
]))

# ═══════════════════════════════════════════════════════════
# 822. Custom Resource Definitions in Kubernetes
# ═══════════════════════════════════════════════════════════
blog_data.append(("Custom Resource Definitions CRDs: Extending Kubernetes Your Way", "custom-resource-definitions-crds-extending-kubernetes", "2020-10-20",
"Master Kubernetes CRDs: schema design, validation, versioning, subresources, and best practices for building custom Kubernetes APIs.",
["Kubernetes", "CRDs", "API", "DevOps"], "devops",
[("What Are Custom Resource Definitions?",
"Custom Resource Definitions (CRDs) allow you to extend Kubernetes with your own API objects without modifying the Kubernetes source code. When you create a CRD, the Kubernetes API server dynamically provisions a new RESTful API endpoint, enabling you to manage instances of your custom resource alongside built-in objects like Pods, Services, and Deployments.\n\nBefore CRDs, extending Kubernetes required building aggregated API servers — a complex undertaking involving deploying a separate API server that registered itself with the main API server. CRDs simplified this dramatically by allowing anyone to define new resource types through a simple YAML manifest. The API server handles all the storage, API routing, admission control, and client generation automatically.\n\nCRDs are used for a wide variety of purposes: defining application-specific configuration (like an IngressRoute for Traefik), representing infrastructure components (like a PostgresCluster for database management), expressing operational intent (like a Backup schedule), or modeling organizational concepts (like a Team or Project). The key design principle is that a CRD should represent a meaningful concept in your domain, not just a wrapper around existing resources."),
("Designing CRD Schemas with OpenAPI v3",
"The schema is the most important part of a CRD definition. It specifies what fields your custom resource supports, their types, default values, and validation rules. Since Kubernetes 1.16, CRDs require a structural OpenAPI v3 schema, which enables server-side validation, client-side code generation, and kubectl explain support.\n\nA well-designed schema follows these principles: use descriptive field names that match the domain language, provide default values for optional fields to reduce boilerplate, use enum types for fields with a fixed set of valid values, and add descriptions to every field for documentation.\n\n```yaml\nschema:\n  openAPIV3Schema:\n    type: object\n    properties:\n      spec:\n        type: object\n        required: [\"replicas\", \"version\"]\n        properties:\n          replicas:\n            type: integer\n            minimum: 1\n            maximum: 10\n            description: \"Number of database replicas\"\n          version:\n            type: string\n            enum: [\"14\", \"15\", \"16\"]\n            description: \"PostgreSQL major version\"\n          storage:\n            type: object\n            properties:\n              size:\n                type: string\n                pattern: \"^[0-9]+(Gi|Mi)$\"\n```\n\nFor complex schemas, use x-kubernetes-preserve-unknown-fields to allow arbitrary JSON in specific sub-trees, and x-kubernetes-embedded-resource for embedding standard Kubernetes resource metadata."),
("CRD Versioning and Conversion Webhooks",
"As your CRD evolves, you may need to introduce breaking changes to the schema. Kubernetes handles this through CRD versioning and conversion mechanisms. A CRD can serve multiple versions simultaneously, with one version marked as the storage version (the version persisted in etcd) and others as served versions (available through the API).\n\nWhen a client requests a resource in a version different from the storage version, Kubernetes converts the resource automatically. For simple structural changes like adding new optional fields, no conversion is needed — Kubernetes handles this through None conversion. For more complex transformations between incompatible versions, you implement a conversion webhook that receives conversion requests and transforms resources between versions.\n\n```yaml\nspec:\n  conversion:\n    strategy: Webhook\n    webhook:\n      clientConfig:\n        service:\n          name: my-converter\n          namespace: default\n          path: /convert\n      conversionReviewVersions: [\"v1\"]\n  versions:\n    - name: v1\n      served: true\n      storage: false\n    - name: v2\n      served: true\n      storage: true\n```\n\nConversion webhooks are stateless HTTP services that receive ConversionReview requests. They must handle both v1-to-v2 and v2-to-v1 conversions. The webhook has a 30-second timeout by default."),
("Subresources: Status and Scale",
"CRDs support two subresources: /status and /scale. The /status subresource separates the specification (spec) from the observed state (status). When you update the status subresource, changes to spec are rejected, and vice versa. This separation is essential for controller-based architectures where the controller updates status to reflect what it has observed, while users update spec to express their desired state.\n\nTo enable the status subresource, add it to the CRD definition:\n```yaml\nversions:\n  - name: v1\n    served: true\n    storage: true\n    subresources:\n      status: {}\n```\n\nThe /scale subresource enables Horizontal Pod Autoscaler (HPA) integration and allows kubectl scale to work with your custom resource. You must specify which fields in the status represent the current replica count and the desired replica count:\n\n```yaml\nsubresources:\n  scale:\n    specReplicasPath: .spec.replicas\n    statusReplicasPath: .status.replicas\n```\n\nAdditional printer columns can be defined to show custom information in kubectl output, making your custom resources more user-friendly:\n\n```yaml\nadditionalPrinterColumns:\n  - name: Replicas\n    type: integer\n    jsonPath: .spec.replicas\n  - name: Version\n    type: string\n    jsonPath: .spec.version\n  - name: Age\n    type: date\n    jsonPath: .metadata.creationTimestamp\n```"),
("Validation, Defaults, and Admission Control",
"Beyond schema-level validation, you can implement more sophisticated validation using admission webhooks. Schema validation can enforce structural correctness — field types, required fields, pattern matching — but it cannot enforce semantic correctness that requires cross-field validation or external lookups.\n\nA validating admission webhook can reject resources that violate complex business rules. For example, a database CRD might require that the storage size can only increase (never decrease), or that production clusters must have at least 3 replicas. The webhook receives an AdmissionReview request containing the proposed resource and returns an AdmissionResponse indicating whether to allow or deny the request.\n\n```python\n@app.route('/validate', methods=['POST'])\ndef validate():\n    review = request.get_json()\n    obj = review['request']['object']\n    allowed = True\n    message = \"\"\n    if obj['spec']['replicas'] < 3 and obj['metadata'].get('labels', {}).get('env') == 'production':\n        allowed = False\n        message = \"Production clusters require at least 3 replicas\"\n    return jsonify({\n        \"apiVersion\": \"admission.k8s.io/v1\",\n        \"kind\": \"AdmissionReview\",\n        \"response\": {\n            \"uid\": review['request']['uid'],\n            \"allowed\": allowed,\n            \"status\": {\"message\": message}\n        }\n    })\n```\n\nMutating webhooks can set defaults, inject sidecars, or add labels. They are called before validating webhooks, so defaults are applied before validation."),
("CRD Best Practices and Common Pitfalls",
"Designing effective CRDs requires careful thought about the API surface, naming conventions, and lifecycle management. One common pitfall is creating CRDs that are too granular — for example, separate CRDs for ConfigMap, Secret, and Deployment configurations when a single application CRD would be more cohesive. Another is creating CRDs that are too generic, essentially mirroring existing Kubernetes resources without adding domain-specific value.\n\nUse API groups to organize related CRDs logically. A database company might use database.example.com for PostgreSQL, MySQL, and Redis CRDs. Plural names should be consistent and follow Kubernetes conventions. Use short names for frequently used resources to reduce typing.\n\nFor production readiness, always enable the status subresource and populate it with meaningful conditions following the Kubernetes conventions (type, status, reason, message, lastTransitionTime). Implement proper finalizers for cleanup when resources are deleted. Use owner references to ensure child resources are garbage collected when the parent CR is deleted.\n\nConsider the impact on the API server: CRDs with very large numbers of instances (tens of thousands) can increase API server memory usage and etcd load. Use namespace-scoped resources when possible, and implement pagination in list operations. Monitor API server performance metrics after introducing CRDs in production."))
])

# ═══════════════════════════════════════════════════════════
# 823. Building Operators with Go and Kubebuilder
# ═══════════════════════════════════════════════════════════
blog_data.append(("Building Kubernetes Operators with Go and Kubebuilder", "building-kubernetes-operators-with-go-and-kubebuilder", "2021-02-10",
"A hands-on guide to building production-grade Kubernetes Operators with Go, kubebuilder, and the controller-runtime library.",
["Kubernetes", "Operators", "Go", "kubebuilder"], "devops",
[("Kubebuilder vs Operator SDK: Choosing Your Framework",
"Kubebuilder and Operator SDK are the two dominant frameworks for building Kubernetes Operators in Go. Both use controller-runtime under the hood, but they differ in their scaffolding philosophy and additional features. Kubebuilder, maintained by the Kubernetes SIG API Machinery, is the more minimal framework that focuses on the core controller-runtime patterns. Operator SDK, maintained by Red Hat and the Operator Framework, builds on kubebuilder and adds features like Helm-based and Ansible-based Operator generation, OLM integration, and scorecard testing.\n\nFor Go-based Operators, the choice between them often comes down to preference and ecosystem needs. If you need OLM integration or want to distribute your Operator through OperatorHub, Operator SDK is the better choice. If you prefer a minimal, Kubernetes-native framework with direct access to controller-runtime, kubebuilder is ideal.\n\nBoth frameworks generate the same core project structure: an api directory for CRD type definitions, a controllers directory for reconciler implementations, a config directory for Kubernetes manifests, and a main.go that sets up the manager. The key difference is in the generated Makefile targets and additional configuration files.\n\nTo install kubebuilder and create a new project:\n```bash\ncurl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)\nchmod +x kubebuilder && mv kubebuilder /usr/local/bin/\nkubebuilder init --domain example.com --repo github.com/example/myoperator\nkubebuilder create api --group app --version v1 --kind MyApp --resource --controller\n```"),
("Defining CRD Types in Go",
"The CRD type definition in Go is the schema for your custom resource. Kubebuilder generates a types file in the api directory that you customize to match your desired specification. The type definition uses kubebuilder markers (comments starting with +) to control code generation, validation, and CRD configuration.\n\n```go\n// +kubebuilder:object:root=true\n// +kubebuilder:subresource:status\n// +kubebuilder:printcolumn:name=\"Replicas\",type=integer,JSONPath=`.spec.replicas`\n// +kubebuilder:printcolumn:name=\"Age\",type=\"date\",JSONPath=`.metadata.creationTimestamp`\ntype MyApp struct {\n    metav1.TypeMeta   `json:\",inline\"`\n    metav1.ObjectMeta `json:\"metadata,omitempty\"`\n    Spec   MyAppSpec   `json:\"spec,omitempty\"`\n    Status MyAppStatus `json:\"status,omitempty\"`\n}\n\ntype MyAppSpec struct {\n    // +kubebuilder:validation:Minimum=1\n    // +kubebuilder:validation:Maximum=10\n    Replicas *int32 `json:\"replicas\"`\n    // +kubebuilder:validation:Enum={\"v1\",\"v2\"}\n    Version string `json:\"version\"`\n    Image   string `json:\"image\"`\n}\n\ntype MyAppStatus struct {\n    Conditions []metav1.Condition `json:\"conditions,omitempty\"`\n    ReadyReplicas int32 `json:\"readyReplicas,omitempty\"`\n}\n```\n\nThe +kubebuilder:validation markers generate OpenAPI v3 validation rules. You can set minimum/maximum for numbers, enum for string choices, pattern for regex validation, and required for mandatory fields. Run make manifests to generate the CRD YAML from these markers."),
("Implementing the Reconciler",
"The reconciler is where all the Operator logic lives. It implements the Reconciler interface from controller-runtime, which has a single method: Reconcile. The controller-runtime Manager calls this method whenever a watched resource changes.\n\n```go\ntype MyAppReconciler struct {\n    client.Client\n    Scheme *runtime.Scheme\n    Log    logr.Logger\n}\n\nfunc (r *MyAppReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {\n    log := r.Log.WithValues(\"myapp\", req.NamespacedName)\n    app := &appv1.MyApp{}\n    if err := r.Get(ctx, req.NamespacedName, app); err != nil {\n        return ctrl.Result{}, client.IgnoreNotFound(err)\n    }\n    // Reconcile Deployment\n    deployment := r.deploymentForApp(app)\n    found := &appsv1.Deployment{}\n    err := r.Get(ctx, types.NamespacedName{Name: app.Name, Namespace: app.Namespace}, found)\n    if err != nil && errors.IsNotFound(err) {\n        log.Info(\"Creating Deployment\", \"name\", deployment.Name)\n        if err = r.Create(ctx, deployment); err != nil {\n            return ctrl.Result{}, err\n        }\n    } else if err == nil {\n        if *found.Spec.Replicas != *app.Spec.Replicas {\n            found.Spec.Replicas = app.Spec.Replicas\n            if err = r.Update(ctx, found); err != nil {\n                return ctrl.Result{}, err\n            }\n        }\n    }\n    return ctrl.Result{}, nil\n}\n```\n\nAlways use server-side apply or create-or-update patterns. Never assume the resource state — always fetch the latest version."),
("Setting Up Watches and Owns Predicates",
"The controller needs to know which resources to watch. The SetupWithManager method configures watches on the primary resource (MyApp) and any secondary resources (Deployments, Services, etc.) that the controller creates and owns.\n\n```go\nfunc (r *MyAppReconciler) SetupWithManager(mgr ctrl.Manager) error {\n    return ctrl.NewControllerManagedBy(mgr).\n        For(&appv1.MyApp{}).\n        Owns(&appsv1.Deployment{}).\n        Owns(&corev1.Service{}).\n        WithEventFilter(predicate.Funcs{\n            UpdateFunc: func(e event.UpdateEvent) bool {\n                return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration()\n            },\n        }).\n        Complete(r)\n}\n```\n\nThe Owns directive sets up watches on owned resources so that changes to child Deployments and Services trigger reconciliation of the parent MyApp. This is essential because if someone manually modifies a child resource, the Operator needs to detect the drift and correct it.\n\nPredicates filter which events trigger reconciliation. The GenerationChangedPredicate is commonly used to ignore status-only updates (where the generation counter does not change), preventing infinite reconciliation loops when the controller itself updates the status.\n\nFor more complex scenarios, you can use WatchesRawSource to watch arbitrary resources, enqueue requests for different objects than the one that changed, or implement custom event handlers."),
("Testing Operators: Unit, Integration, and End-to-End",
"Testing Kubernetes Operators requires a layered approach. Unit tests verify individual functions — helper methods, resource builders, and utility logic — without any Kubernetes infrastructure. Integration tests use the envtest package from controller-runtime, which starts a real API server and etcd binary locally, allowing you to test the full reconciliation loop against real Kubernetes API behavior.\n\n```go\nvar testEnv *envtest.Environment\nvar _ = BeforeSuite(func() {\n    testEnv = &envtest.Environment{\n        CRDDirectoryPaths: []string{filepath.Join(\"..\", \"..\", \"config\", \"crd\", \"bases\")},\n    }\n    cfg, err := testEnv.Start()\n    Expect(err).NotTo(HaveOccurred())\n})\n\nvar _ = AfterSuite(func() {\n    testEnv.Stop()\n})\n```\n\nIntegration tests create custom resources, wait for reconciliation, and verify that expected child resources were created. Use Gomega's Eventually for async assertions:\n\n```go\nIt(\"should create a deployment\", func() {\n    myapp := &appv1.MyApp{...}\n    Expect(k8sClient.Create(ctx, myapp)).Should(Succeed())\n    Eventually(func() int32 {\n        deploy := &appsv1.Deployment{}\n        k8sClient.Get(ctx, key, deploy)\n        return deploy.Status.ReadyReplicas\n    }, timeout, interval).Should(Equal(int32(3)))\n})\n```\n\nEnd-to-end tests run against a real cluster using kind or k3d, testing the complete lifecycle including image pulls and pod scheduling."))
])

print(f"Prepared {len(blog_data)} blogs so far...")
